#!/usr/bin/env node
// Builds the CMS semantic layer from src/assets/tokens/semantic.json:
// theme blocks (colour, overlay, shadow), the $semantic-classes map main.scss turns into utility classes,
// and the .type-<role> classes. Brand references become var(--brand-*), never hex.
// Usage: node scripts/tokens/build-theme.mjs [output path]
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ROOT = new URL("../../", import.meta.url);
const SOURCE = new URL("src/assets/tokens/semantic.json", ROOT);
const OUTPUT = new URL("src/assets/scss/themes/_semantic.generated.scss", ROOT);
const THEMES = { dark: "dark", light: "default" };
const FAMILIES = { text: ["t"], surface: ["bg"], border: ["b"], accent: ["t", "bg", "b"], status: ["t", "bg", "b"] };
const FONT_FAMILIES = { brand: "var(--font-brand)", ui: "var(--font-ui)" };

const entries = (group) => Object.entries(group).filter(([key]) => !key.startsWith("$"));

function brandVars() {
  const css = readFileSync(fileURLToPath(import.meta.resolve("@entirius/brand-tokens/tokens.css")), "utf8");
  return new Set([...css.matchAll(/(--brand-[\w-]+):/g)].map((m) => m[1]));
}

// "{light.basic.50}" → "var(--brand-light-basic-50)"; raw values pass through.
function resolver(known) {
  return (raw) => {
    const ref = String(raw).match(/^\{(.+)\}$/);
    if (!ref) return String(raw);
    const name = `--brand-${ref[1].replaceAll(".", "-")}`;
    if (!known.has(name)) throw new Error(`${raw}: ${name} is not defined by @entirius/brand-tokens`);
    return `var(${name})`;
  };
}

const themeTokens = (map) => [
  ...Object.values(map.color).flatMap(entries),
  ...entries(map.overlay),
  ...entries(map.shadow),
];

function themeBlock(map, theme, resolve) {
  const lines = themeTokens(map).map(([name, token]) => `  --${name}: ${resolve(token[theme])};`);
  return `[data-theme="${THEMES[theme]}"] {\n${lines.join("\n")}\n}`;
}

const classTokens = (map) =>
  Object.entries(map.color).flatMap(([group, tokens]) =>
    entries(tokens)
      .filter(([, token]) => token.class !== null)
      .map(([name, token]) => ({ name, token, group, suffix: (token.class ?? name).replace(/^(t|bg|b)-/, "") }))
  );

// The first token to claim a class keeps it: `.t-accent` is text-accent, so accent emits only `.bg-`/`.b-accent`.
function classRows(map) {
  const claimed = new Set();
  const rows = classTokens(map).map((row) => {
    const families = FAMILIES[row.group].filter((family) => !claimed.has(`${family}-${row.suffix}`));
    families.forEach((family) => claimed.add(`${family}-${row.suffix}`));
    return { ...row, families };
  });
  // `.t-accent-hover` is a token class of its own, so `.t-accent` gets no `-hover:hover` variant.
  const hover = ({ families, suffix }) => !families.some((family) => claimed.has(`${family}-${suffix}-hover`));
  return rows.filter((row) => row.families.length).map((row) => ({ ...row, hover: hover(row) }));
}

function classMap(map) {
  const rows = classRows(map).map(({ name, token, families, suffix, hover }) => {
    const background = token.type === "background" ? "background" : "background-color";
    return `  "${name}": (name: "${suffix}", families: ${families.join(" ")}, hover: ${hover}, background: ${background}),`;
  });
  return `$semantic-classes: (\n${rows.join("\n")}\n);`;
}

function typeRole([role, spec], resolve) {
  const declarations = [
    `font-family: ${FONT_FAMILIES[spec.family]}`,
    `font-weight: ${spec.weight}`,
    `font-size: ${spec.size}`,
    `line-height: ${spec.line}`,
    `letter-spacing: ${resolve(spec.tracking)}`,
    ...(spec.case ? [`text-transform: ${spec.case}`] : []),
  ];
  return `.type-${role} {\n${declarations.map((d) => `  ${d};`).join("\n")}\n}`;
}

function buildTheme() {
  const map = JSON.parse(readFileSync(SOURCE, "utf8"));
  const resolve = resolver(brandVars());
  return [
    "// Generated by scripts/tokens/build-theme.mjs from src/assets/tokens/semantic.json — do not edit.\n" +
      "// Regenerate: node scripts/tokens/build-theme.mjs",
    themeBlock(map, "dark", resolve),
    themeBlock(map, "light", resolve),
    classMap(map),
    ...entries(map.type).map((role) => typeRole(role, resolve)),
  ].join("\n\n") + "\n";
}

writeFileSync(process.argv[2] ?? OUTPUT, buildTheme());
