import { AREAS } from "@/configs/areas";

// The panel registry: one entry per CMS panel. `areas` are the django-access areas the panel works on (the area
// catalogue keys); a panel is shown when the user can read any of them (`useAccessStore().canAny`).
export const panels = [
  {
    name: "Pages",
    idx: "pages",
    icon: "file-code",
    root: "/pages/content",
    labelKey: "panels.pages",
    descriptionKey: "panels.pages_desc",
    areas: [AREAS.CONTENT_PAGES, AREAS.CONTENT_PUBLISH, AREAS.CONTENT_MEDIA, AREAS.CONTENT_SCHEMA],
  },
  {
    name: "PIM",
    idx: "pim",
    icon: "boxes-stacked",
    root: "/pim/products",
    labelKey: "panels.pim",
    descriptionKey: "panels.pim_desc",
    areas: [AREAS.PIM_PRODUCTS, AREAS.PIM_CATEGORIES, AREAS.PIM_SCHEMA, AREAS.PIM_QUALITY, AREAS.SUPPLIERS_SOURCES, AREAS.SUPPLIERS_PRODUCTS],
  },
  {
    name: "Points",
    idx: "points",
    icon: "location-dot",
    root: "/points/list",
    labelKey: "panels.points",
    descriptionKey: "panels.points_desc",
    areas: [AREAS.DELIVERYPOINTS_POINTS],
  },
  {
    name: "Forms",
    idx: "forms",
    icon: "envelope",
    root: "/forms/list",
    labelKey: "panels.forms",
    descriptionKey: "panels.forms_desc",
    areas: [AREAS.CONTACT_FORMS_SUBMISSIONS, AREAS.CONTACT_FORMS_LEADS, AREAS.CONTACT_FORMS_SETTINGS],
  },
  {
    name: "Accounts",
    idx: "accounts",
    icon: "users",
    root: "/accounts/customers",
    labelKey: "panels.accounts",
    descriptionKey: "panels.accounts_desc",
    areas: [AREAS.ACCOUNTS_CUSTOMERS],
  },
  {
    name: "Orders",
    idx: "checkout",
    icon: "shopping-cart",
    root: "/checkout-orders/orders",
    labelKey: "panels.checkout_orders",
    descriptionKey: "panels.checkout_orders_desc",
    areas: [AREAS.CHECKOUT_ORDERS],
  },
  {
    name: "Agreements",
    idx: "agreements",
    icon: "file-contract",
    root: "/agreements/list",
    labelKey: "panels.agreements",
    descriptionKey: "panels.agreements_desc",
    areas: [AREAS.AGREEMENTS_DEFINITIONS, AREAS.AGREEMENTS_CONSENTS],
  },
  {
    name: "Emails",
    idx: "emails",
    icon: "at",
    root: "/emails",
    labelKey: "panels.emails",
    descriptionKey: "panels.emails_desc",
    areas: [AREAS.EMAIL_TEMPLATES],
  },
  {
    name: "FAQ",
    idx: "faq",
    icon: "circle-question",
    root: "/faq/groups",
    labelKey: "panels.faq",
    descriptionKey: "panels.faq_desc",
    areas: [AREAS.FAQ_FAQ],
  },
  {
    name: "Pricing",
    idx: "pricing",
    icon: "money-bill-wave",
    root: "/pricing/prices",
    labelKey: "panels.pricing",
    descriptionKey: "panels.pricing_desc",
    areas: [AREAS.PRICEMANAGER_PRICES, AREAS.PRICEMANAGER_SETTINGS],
  },
  {
    name: "Stock",
    idx: "stock",
    icon: "warehouse",
    root: "/stock/manage",
    labelKey: "panels.stock",
    descriptionKey: "panels.stock_desc",
    areas: [AREAS.QMS_STOCK],
  },
  {
    name: "Translation",
    idx: "translation",
    icon: "language",
    root: "/translation-jobs",
    labelKey: "panels.translation",
    descriptionKey: "panels.translation_desc",
    areas: [AREAS.PIM_TRANSLATOR_TRANSLATE, AREAS.CONTENTDB_TRANSLATOR_TRANSLATE],
  },
  {
    name: "Atlas",
    idx: "atlas",
    icon: "globe",
    root: "/atlas/list",
    labelKey: "panels.atlas",
    descriptionKey: "panels.atlas_desc",
    areas: [AREAS.ATLAS_SOURCES, AREAS.ATLAS_PRODUCTS, AREAS.ATLAS_CREDENTIALS, AREAS.LOOKUP_SEARCH],
  },
  {
    name: "Enricher",
    idx: "enricher",
    icon: "wand-magic-sparkles",
    root: "/enrichment",
    labelKey: "panels.enricher",
    descriptionKey: "panels.enricher_desc",
    areas: [AREAS.ENRICHMENT_RULES, AREAS.ENRICHMENT_PROPOSALS],
  },
  {
    name: "Promo",
    idx: "promo",
    icon: "tags",
    root: "/promo/list",
    labelKey: "panels.promo",
    descriptionKey: "panels.promo_desc",
    areas: [AREAS.CHECKOUT_DISCOUNTS],
  },
  {
    name: "PriceFighter",
    idx: "pricefighter",
    icon: "scale-balanced",
    root: "/pricefighter/gap",
    labelKey: "panels.pricefighter",
    descriptionKey: "panels.pricefighter_desc",
    areas: [AREAS.PRICEFIGHTER_DECISIONS, AREAS.PRICEFIGHTER_RULES],
  },
  {
    name: "Leads",
    idx: "leads",
    icon: "inbox",
    root: "/leads/inbox",
    // the Inbox needs django-communicator; a leads-only backend opens the company list (phone-usable)
    fallback: "/leads/companies",
    labelKey: "panels.leads",
    descriptionKey: "panels.leads_desc",
    areas: [
      AREAS.LEADS_COMPANIES,
      AREAS.LEADS_SETTINGS,
      AREAS.LEADS_GDPR,
      AREAS.COMMUNICATOR_REVIEW,
      AREAS.COMMUNICATOR_CONTENT,
      AREAS.COMMUNICATOR_CONVERSATIONS,
      AREAS.COMMUNICATOR_SETTINGS,
      AREAS.SITEINTEL_AUDITS,
    ],
  },
  {
    name: "Access",
    idx: "access",
    icon: "user-shield",
    root: "/access/roles",
    labelKey: "panels.access",
    descriptionKey: "panels.access_desc",
    areas: [AREAS.ACCESS_MANAGE],
  },
];

export const User = class {
  constructor({ username = "namelessking", first_name = "", last_name = "", email = "", buildTypes = [] }) {
    this.username = username;
    this.first_name = first_name;
    this.last_name = last_name;
    this.email = email;
    this.buildTypes = buildTypes;
  }
};
