// The panel registry: one entry per CMS panel. `areas` are the django-access areas the panel works on (the area
// catalogue keys); a panel is shown when the user can read any of them (`useAccessStore().canAny`).
export const panels = [
  {
    name: "Pages",
    idx: "pages",
    icon: "file-code",
    root: "/pages/content",
    labelKey: "panels.pages",
    descriptionKey: "panels.pages_desc",
    areas: ["content.pages", "content.publish", "content.media", "content.schema"],
  },
  {
    name: "PIM",
    idx: "pim",
    icon: "boxes-stacked",
    root: "/pim/products",
    labelKey: "panels.pim",
    descriptionKey: "panels.pim_desc",
    areas: ["pim.products", "pim.categories", "pim.schema", "pim.quality", "suppliers.sources", "suppliers.products"],
  },
  {
    name: "Points",
    idx: "points",
    icon: "location-dot",
    root: "/points/list",
    labelKey: "panels.points",
    descriptionKey: "panels.points_desc",
    areas: ["deliverypoints.points"],
  },
  {
    name: "Forms",
    idx: "forms",
    icon: "envelope",
    root: "/forms/list",
    labelKey: "panels.forms",
    descriptionKey: "panels.forms_desc",
    areas: ["contact_forms.submissions", "contact_forms.leads", "contact_forms.settings"],
  },
  {
    name: "Accounts",
    idx: "accounts",
    icon: "users",
    root: "/accounts/customers",
    labelKey: "panels.accounts",
    descriptionKey: "panels.accounts_desc",
    areas: ["accounts.customers"],
  },
  {
    name: "Orders",
    idx: "checkout",
    icon: "shopping-cart",
    root: "/checkout-orders/orders",
    labelKey: "panels.checkout_orders",
    descriptionKey: "panels.checkout_orders_desc",
    areas: ["checkout.orders"],
  },
  {
    name: "Agreements",
    idx: "agreements",
    icon: "file-contract",
    root: "/agreements/list",
    labelKey: "panels.agreements",
    descriptionKey: "panels.agreements_desc",
    areas: ["agreements.definitions", "agreements.consents"],
  },
  {
    name: "Emails",
    idx: "emails",
    icon: "at",
    root: "/emails",
    labelKey: "panels.emails",
    descriptionKey: "panels.emails_desc",
    areas: ["email.templates"],
  },
  {
    name: "FAQ",
    idx: "faq",
    icon: "circle-question",
    root: "/faq/groups",
    labelKey: "panels.faq",
    descriptionKey: "panels.faq_desc",
    areas: ["faq.faq"],
  },
  {
    name: "Pricing",
    idx: "pricing",
    icon: "money-bill-wave",
    root: "/pricing/prices",
    labelKey: "panels.pricing",
    descriptionKey: "panels.pricing_desc",
    areas: ["pricemanager.prices", "pricemanager.settings"],
  },
  {
    name: "Stock",
    idx: "stock",
    icon: "warehouse",
    root: "/stock/manage",
    labelKey: "panels.stock",
    descriptionKey: "panels.stock_desc",
    areas: ["qms.stock"],
  },
  {
    name: "Translation",
    idx: "translation",
    icon: "language",
    root: "/translation-jobs",
    labelKey: "panels.translation",
    descriptionKey: "panels.translation_desc",
    areas: ["pim_translator.translate", "contentdb_translator.translate"],
  },
  {
    name: "Atlas",
    idx: "atlas",
    icon: "globe",
    root: "/atlas/list",
    labelKey: "panels.atlas",
    descriptionKey: "panels.atlas_desc",
    areas: ["atlas.sources", "atlas.products", "atlas.credentials", "lookup.search"],
  },
  {
    name: "Enricher",
    idx: "enricher",
    icon: "wand-magic-sparkles",
    root: "/enrichment",
    labelKey: "panels.enricher",
    descriptionKey: "panels.enricher_desc",
    areas: ["enrichment.rules", "enrichment.proposals"],
  },
  {
    name: "Promo",
    idx: "promo",
    icon: "tags",
    root: "/promo/list",
    labelKey: "panels.promo",
    descriptionKey: "panels.promo_desc",
    areas: ["checkout.discounts"],
  },
  {
    name: "PriceFighter",
    idx: "pricefighter",
    icon: "scale-balanced",
    root: "/pricefighter/gap",
    labelKey: "panels.pricefighter",
    descriptionKey: "panels.pricefighter_desc",
    areas: ["pricefighter.decisions", "pricefighter.rules"],
  },
  {
    name: "Leads",
    idx: "leads",
    icon: "inbox",
    root: "/leads/inbox",
    // the Inbox needs django-communicator; a leads-only backend opens the company list (phone-usable)
    fallback: "/leads/companies",
    labelKey: "panels.leads",
    descriptionKey: "panels.leads_desc",
    areas: [
      "leads.companies",
      "leads.settings",
      "leads.gdpr",
      "communicator.review",
      "communicator.content",
      "communicator.conversations",
      "communicator.settings",
      "siteintel.audits",
    ],
  },
  {
    name: "Access",
    idx: "access",
    icon: "user-shield",
    root: "/access/roles",
    labelKey: "panels.access",
    descriptionKey: "panels.access_desc",
    areas: ["access.manage"],
  },
];

export const User = class {
  constructor({ username = "namelessking", first_name = "", last_name = "", email = "", buildTypes = [] }) {
    this.username = username;
    this.first_name = first_name;
    this.last_name = last_name;
    this.email = email;
    this.buildTypes = buildTypes;
  }
};
