// The django-access area keys the CMS refers to (routes' `meta.area`, the panel registry, in-view `can()` checks), one
// constant per catalogue key (`GET /api/access/v2/admin/catalogue/`), in catalogue order. Import from here, never
// spell a key: a renamed area is one edit. `tests/unit/configs/areas.spec.js` keeps every value in the catalogue
// snapshot (`tests/fixtures/access-catalogue.json`).
export const AREAS = Object.freeze({
  PIM_PRODUCTS: "pim.products",
  PIM_CATEGORIES: "pim.categories",
  PIM_SCHEMA: "pim.schema",
  PIM_QUALITY: "pim.quality",
  PIM_PRODUCT_DELETE: "pim.product_delete",
  PIM_TRANSLATOR_TRANSLATE: "pim_translator.translate",
  PRICEMANAGER_PRICES: "pricemanager.prices",
  PRICEMANAGER_SETTINGS: "pricemanager.settings",
  PRICEFIGHTER_DECISIONS: "pricefighter.decisions",
  PRICEFIGHTER_RULES: "pricefighter.rules",
  QMS_STOCK: "qms.stock",
  SUPPLIERS_SOURCES: "suppliers.sources",
  SUPPLIERS_PRODUCTS: "suppliers.products",
  ATLAS_SOURCES: "atlas.sources",
  ATLAS_PRODUCTS: "atlas.products",
  ATLAS_CREDENTIALS: "atlas.credentials",
  ENRICHMENT_RULES: "enrichment.rules",
  ENRICHMENT_PROPOSALS: "enrichment.proposals",
  LOOKUP_SEARCH: "lookup.search",
  CONTENT_PAGES: "content.pages",
  CONTENT_PUBLISH: "content.publish",
  CONTENT_MEDIA: "content.media",
  CONTENT_SCHEMA: "content.schema",
  CONTENTDB_TRANSLATOR_TRANSLATE: "contentdb_translator.translate",
  FAQ_FAQ: "faq.faq",
  DELIVERYPOINTS_POINTS: "deliverypoints.points",
  EMAIL_TEMPLATES: "email.templates",
  AGREEMENTS_DEFINITIONS: "agreements.definitions",
  AGREEMENTS_CONSENTS: "agreements.consents",
  ACCOUNTS_CUSTOMERS: "accounts.customers",
  CHECKOUT_ORDERS: "checkout.orders",
  CHECKOUT_DISCOUNTS: "checkout.discounts",
  CONTACT_FORMS_SUBMISSIONS: "contact_forms.submissions",
  CONTACT_FORMS_LEADS: "contact_forms.leads",
  CONTACT_FORMS_SETTINGS: "contact_forms.settings",
  LEADS_COMPANIES: "leads.companies",
  LEADS_SETTINGS: "leads.settings",
  LEADS_GDPR: "leads.gdpr",
  COMMUNICATOR_REVIEW: "communicator.review",
  COMMUNICATOR_CONTENT: "communicator.content",
  COMMUNICATOR_CONVERSATIONS: "communicator.conversations",
  COMMUNICATOR_SETTINGS: "communicator.settings",
  SITEINTEL_AUDITS: "siteintel.audits",
  ACCESS_MANAGE: "access.manage",
});
