// Icon meaning registry (docs/ui-rules.md C5, R6): one meaning → one FontAwesome glyph, one glyph → one meaning.
// Templates pick a meaning, never a glyph: `<FontAwesomeIcon :icon="$icons.edit" />`. Keys are camelCase so every
// meaning reads as `$icons.<key>`. Every glyph is registered in fa-icons.js (tests/unit/boots/icons.spec.js).
// Stream-1 file: a stream-2 plan uses the closest meaning and hands a new one to plan 19.
// Panel and page glyphs of the navigation (configs/access.js, components/Navigation/nav-routes.js) are the P4
// nav model's, not meanings.
export const ICONS = Object.freeze({
  // Figma (r02 § Icons) and the synonyms folded into one glyph each
  add: "plus",
  edit: "pen",
  delete: "trash-can",
  duplicate: "copy",
  close: "xmark",
  back: "arrow-left",
  search: "magnifying-glass",
  settings: "gears",
  preview: "eye",
  hide: "eye-slash",
  channels: "globe",
  saveDraft: "floppy-disk",
  publish: "upload",
  reorder: "arrows-up-down",
  drag: "grip-vertical",
  menu: "grip",
  more: "ellipsis-vertical",
  expand: "chevron-down",
  collapse: "chevron-up",
  prev: "chevron-left",
  next: "chevron-right",
  lock: "lock",
  user: "user",
  download: "download",
  import: "file-import",
  importCsv: "file-csv",
  refresh: "rotate",
  info: "circle-info",
  help: "circle-question",
  warning: "triangle-exclamation",
  success: "circle-check",
  translate: "language",
  filter: "filter",
  link: "link",
  external: "up-right-from-square",
  logout: "arrow-right-from-bracket",
  themeDark: "moon",
  themeLight: "sun",
  notifications: "bell",
  check: "check",
  calendar: "calendar-days",
  image: "image",
  // Census of the glyphs src/ uses that no Figma meaning covers
  upload: "file-arrow-up",
  moveUp: "arrow-up",
  moveDown: "arrow-down",
  primary: "star",
  file: "file",
  attachment: "paperclip",
  password: "key",
  scheduled: "clock",
  history: "clock-rotate-left",
  send: "paper-plane",
  target: "bullseye",
  video: "video",
  play: "play",
  category: "folder",
  categories: "folder-tree",
  variants: "diagram-next",
  enrich: "wand-magic-sparkles",
  tag: "tag",
  home: "house",
  author: "user-pen",
  clear: "broom",
  checkboxOn: "square-check",
  checkboxOff: "square",
  fullscreen: "expand",
  exitFullscreen: "compress",
});
