<template>
  <BasicModal
    :open="open"
    :title="$t('access.staff.create')"
    size="md"
    :persistent="busy"
    :actions="actions"
    data-testid="staff-create-dialog"
    @update:open="(next) => !next && close()"
  >
    <div class="flex-column gap-4">
      <FormField :label="$t('access.staff.username')" required :error="fieldError('username')">
        <BasicInput v-model="form.username" :maxlength="150" autocomplete="off" data-testid="staff-create-username" />
      </FormField>
      <FormField :label="$t('access.staff.email')" required :error="fieldError('email')">
        <BasicInput
          v-model="form.email"
          format="email"
          :maxlength="254"
          autocomplete="off"
          data-testid="staff-create-email"
        />
      </FormField>
      <FormField :label="$t('access.staff.role')" required :error="fieldError('role')">
        <BasicSelect v-model="form.role" :options="roleOptions" data-testid="staff-create-role" />
      </FormField>
      <FormField
        :label="$t('access.staff.password')"
        :hint="form.generate ? $t('access.staff.generate_hint') : ''"
        hint-level="important"
        :error="fieldError('password')"
      >
        <div class="flex-column gap-2">
          <BasicCheckbox v-model="form.generate" data-testid="staff-create-generate">
            {{ $t("access.staff.generate_password") }}
          </BasicCheckbox>
          <BasicInput
            v-if="!form.generate"
            v-model="form.password"
            type="password"
            autocomplete="new-password"
            :aria-label="$t('access.staff.password')"
            data-testid="staff-create-password"
          />
        </div>
      </FormField>
    </div>
  </BasicModal>
</template>

<script setup>
// New staff member (D1): username, e-mail, one role and the password — generated by the server (the default) or typed.
// `submit(payload)` is the page's call: it hands a generated password straight to SecretReveal, the dialog never sees
// it. A refusal that names a field (400 details, 409 on a taken username or e-mail) stays open on that field; any other
// closes with the server's message. No client-side password rules: the server's validators are the one source. A typed
// password leaves the form on close.
import { computed, reactive, ref, watch } from "vue";
import { t } from "@/i18n";
import { isConflict } from "@/api/createClient";
import { useNotifyStore } from "@/stores/notify";
import { useFormErrors, extractApiMessage } from "@/composables/useFormErrors";

const FIELDS = ["username", "email", "role", "password"];
const EMPTY = { username: "", email: "", role: null, generate: true, password: "" };

const props = defineProps({
  open: { type: Boolean, default: false },
  roles: { type: Array, default: () => [] },
  submit: { type: Function, required: true },
});
const emit = defineEmits(["update:open"]);

const form = reactive({ ...EMPTY });
const busy = ref(false);
const formErrors = useFormErrors();
const notify = useNotifyStore();

const roleOptions = computed(() => props.roles.map((role) => ({ label: role.name, value: role.key })));
const fieldError = (field) => formErrors.getFieldError(field)?.msg || "";
const complete = computed(() => form.username && form.email && form.role && (form.generate || form.password));

watch(
  () => props.open,
  (open) => !open && Object.assign(form, EMPTY)
);
// Back to Generate drops a typed password: it is never kept for a later send.
watch(
  () => form.generate,
  (generate) => generate && (form.password = "")
);
// An edit after a refusal clears its field errors: a fixed field never keeps the old sentence.
watch(form, () => formErrors.hasErrors.value && formErrors.clearErrors());

function close() {
  formErrors.clearErrors();
  emit("update:open", false);
}

function payload() {
  const { username, email, role, generate, password } = form;
  return generate ? { username, email, role } : { username, email, role, password };
}

// Every validator message of a field, not only the last (a weak password fails several at once).
function fieldMessages(err, field) {
  const details = err?.details ?? err?.response?.data?.details ?? [];
  return details
    .filter((d) => String(d.field).split(".").pop() === field)
    .map((d) => d.description)
    .join(" ");
}

// A 409 names no field: the server's sentence says which one is taken.
function conflictField(err) {
  return /e-?mail/i.test(extractApiMessage(err)) ? "email" : "username";
}

function showRefusal(err) {
  formErrors.handleApiError(err);
  if (isConflict(err)) formErrors.errors[conflictField(err)] = { status: "error", msg: extractApiMessage(err) };
  const password = fieldMessages(err, "password");
  if (password) formErrors.errors.password = { status: "error", msg: password };
  if (FIELDS.some((field) => formErrors.getFieldError(field))) return;
  notify.spawnNotification({ type: "negative", msg: extractApiMessage(err, t("notifications.error")) });
  close();
}

async function save() {
  busy.value = true;
  try {
    await props.submit(payload());
  } catch (err) {
    showRefusal(err);
  } finally {
    busy.value = false;
  }
}

const actions = computed(() => [
  { key: "cancel", role: "secondary", label: t("common.cancel"), onClick: close, disabled: busy.value },
  {
    key: "create",
    role: "primary",
    label: t("access.staff.create"),
    onClick: save,
    disabled: !complete.value,
    loading: busy.value,
    testid: "staff-create-save",
  },
]);
</script>
